### PR TITLE
[FE] Display all learnt words on words learnt page

### PR DESCRIPTION
**Pull request by Vali-R**
## Asana Link
https://app.asana.com/0/1202860323783357/1202865733590566/f

 ## Commands
```
cd backend
npm start

cd frontend
npm start
```
**Please go to `learnings` page (red circle in the picture below)**

## Pre-conditions

- **Please undo your migration and redo it, the commands are followings:**

Undo migration
```
npx sequelize-cli db:migrate:undo:all
```
Migrate
```
px sequelize-cli db:migrate
```
Seeding
```
npx sequelize-cli db:seed --seed 20220831071727-User.js  20220901231553-Quiz.js 20220901231334-UserLesson.js 20220901231240-Follow.js  20220901231127-ActivityLog.js 20220901231658-Question.js 20220901231713-UserAnswer.js
```

## Expected Output

- [x]  **Responsive design**
- [x] **Should be able to display all learnt words with their lesson names of any user** 
- [x] **You should be able to go back to user's profile from the page** 

## Documentation
- Postman APIs - https://grey-firefly-150180.postman.co/workspace/e-learning~b9d71430-452d-47cc-8c64-e2b2e960bd99/example/22825265-04fdb3a0-77bc-42fe-8dae-153965b37c87

## Notes
**Backend and Frontend integration**

 ## Screenshots

image

image

### CODE REVIEW

**Review by escbooster12-dev — COMMENTED** [review]
Comment

- [x] Current implementation is, even the words were answered incorrectly, it still considered as _learnt_, which is not correct. The learned words are supposed to be the words that were answered correctly. 
- [x] It should let the user take the lesson again until he perfectly answered it.

**Comment by escbooster12-dev** [comment]
Comment
- [ ] when retake the previous answer were displayed. When retaking the lesson, previous answer should be cleared or reset.
- [ ] i observed correct answers were always displayed at the choice/option "D". Please shuffle the choices so that correct answer could not be easily predicted.

https://user-images.githubusercontent.com/73863685/191656451-1d3d61e6-b0a2-4a17-9f5c-d83c42c2fab5.mp4

<hr>

Total comments: 4
Iteration: 2

**Comment by escbooster12-dev** [comment]
>[@esca](https://sun-philippine.slack.com/team/U02AWTP13BM)
 I do have shuffle function for my questions but it is only when user takes the lesson, I did not add shuffle for result because even If I did, it would not be the same shuffle as it was during the lesson, and as far as the cleaning the answers are concerned I actually already have that but I just realized that I forgot to add it to precondition that you need to undo migration and redo it so the cleaning function will work, I'll add it in the preconditions rn
i just realized now, there has something wrong in your erd. There should be 4 choices in your questions table. and another column for correct_answer.

Right now when I logout and login and view the result, i can now longer see my answer.
image

**Comment by Vali-R** [comment]
> > [@esca](https://sun-philippine.slack.com/team/U02AWTP13BM)
> > I do have shuffle function for my questions but it is only when user takes the lesson, I did not add shuffle for result because even If I did, it would not be the same shuffle as it was during the lesson, and as far as the cleaning the answers are concerned I actually already have that but I just realized that I forgot to add it to precondition that you need to undo migration and redo it so the cleaning function will work, I'll add it in the preconditions rn
> 
> i just realized now, there has something wrong in your erd. There should be 4 choices in your questions table. and another column for correct_answer.
> 
> Right now when I logout and login and view the result, i can no longer see my answer. image

@escbooster12-dev 
That is the effect of my change on DB, currently since it cannot find my change from your DB, it is returning a null for user's answers,  please redo the migration and everything should work fine again

**Comment by escbooster12-dev** [comment]
Comment
- [ ] i already run the commands from the preconditions, but the problem below still occurs
>Right now when I logout and login and view the result, i can no longer see my answer.

<details>
<summary> Screenshots </summary>

image
</details>

- [ ] i just realized now, there has something wrong in your erd. There should be 4 choices in your questions table. and another column for correct_answer.

<hr>

Total comments: 6
Iteration: 3

**Review by escbooster12-dev — APPROVED** [review]

**Pull request merged**
